# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Deploy Development build to Firebase"
    lane :distribute_development do
        firebase_app_distribution(
            app: "1:648236039306:ios:2eccdbb735b0ce83340173",
            ipa_path: "../build/ios/iphoneos/app-development-release.ipa",
            firebase_cli_token: "$FIREBASE_TOKEN",
            groups: "bitbox, qa, drd"
        )
    end

    desc "Deploy Development Nightly build to Firebase"
    lane :distribute_development_nightly do
        firebase_app_distribution(
            app: "1:648236039306:ios:2eccdbb735b0ce83340173",
            ipa_path: "../build/ios/iphoneos/app-development-release.ipa",
            firebase_cli_token: "$FIREBASE_TOKEN",
            release_notes_file: "release_notes.txt",
            groups: "bitbox, qa, drd"
        )
    end
end
